#ifndef DEF_SCHOLOMANCE_H
#define DEF_SCHOLOMANCE_H

enum Data
{
    DATA_JANDICE_BAROV,
    DATA_RATTLEGORE,
    DATA_LILLIAN_VOSS,
    DATA_LILLIAN_VOSS_SOUL,
    DATA_GANDLING,
    MAX_ENCOUNTER
};

enum BossEntrys
{
    BOSS_JANDICE_BAROV        = 59184,
    BOSS_RATTLEGORE           = 67273,
    BOSS_LILLIAN_VOSS         = 67274,
    BOSS_LILLIAN_VOSS_SOUL    = 58791,
    BOSS_DARKMASTER_GANDLING  = 67275
};

enum Creatures
{
    CREATURE_JANDICE_ILLUSION = 59220,
    CREATURE_GRAVITY_FLUX     = 67272,
    CREATURE_BONE_PILE        = 59304
};

#endif
